# Generated by Django 4.0.6 on 2024-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestroProducto',
            fields=[
                ('idp', models.IntegerField(primary_key=True, serialize=False)),
                ('nomprod', models.CharField(max_length=100)),
                ('descprod', models.CharField(max_length=300)),
                ('precio', models.IntegerField()),
                ('foto_prod', models.ImageField(default='prod.jpg', upload_to='imagenes', verbose_name='Imagen')),
            ],
        ),
    ]
