# Generated by Django 4.0.6 on 2024-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maestroproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroproducto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
