# Generated by Django 4.0.6 on 2024-05-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroproducto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
